databases:
  - name: rendertest
    databaseName: rendertest
    user: rendertest

services:
  - type: web
    name: rendertest
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rendertest
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
